### ISSUE TITLE
After installing using SMM, Staisfactory won't start.

### ISSUE THREAD

**Issue by kilsbo** [TwoTwoEleven/MicroManage#8]
...I get to the point loading Satisfactory, with a dialogue box stating:

"Plugin 'MicroManage' failed to load because module 'MicroManage' could not be loaded. There may be an operating system error or the module may not be properly setup."

After clicking the only available button, "OK", Satisfactory exits.

I really wish I had more details, but I can't get past this. Removing the mod in SMM solves the problem, albeit without being able to enjoy this mod.

Windows 10, fully patched, same with Steam.

Cheers,
Ronnie

**Comment by TwoTwoEleven** [comment]
Fixed in the 0.9.6 release.

**Comment by matbrodi** [comment]
Got to reactivate this issue.
I have MicroMan 0.9.6 istalled via
SMM 2.4.3 on Satis Experimental and still get the error message on start
![Satis MicroMan Message](https://user-images.githubusercontent.com/82906437/116792863-9c25ce00-aac3-11eb-9244-42035bb6c512.png)

Removed and reinstalled it multiple time and checked that it was removed and that the installed version was 0.9.6 in the 
steamapps\common\Satisfactory\FactoryGame\Mods\MicroManage\MicroManage.uplugin

**Comment by TwoTwoEleven** [comment]
This is outside of MicroManage scope since SML is not working on Experimental right now.  Should work on Early Access.
